// Generated by scripts/crafting-history.ts. Historical implementations are retained in crafting-history/.
import type { HistoricalCraftingRuntime } from "./crafting-runtime";
import * as runtime0 from "../../crafting-history/engines/296f9f16b2e0d52352368ef18c220fc5926eb89ec0f360aef0456c191efbd8b1.mjs";
import * as runtime1 from "../../crafting-history/engines/b57317f7f65b2ea389c23aceccb86932e9e7d431793467b11f8b88a145a7e802.mjs";
import * as runtime2 from "../../crafting-history/engines/04c86b667516300ef56642d9e6c220a76e4c9be0a5c363e4b93fc263c26c7d1f.mjs";
import * as runtime3 from "../../crafting-history/engines/e7614802f36cc80d556ce55837ca5844e92674f3c76f659dcc10d0ccd0b984c2.mjs";
import * as runtime4 from "../../crafting-history/engines/cbcbe51dc69b80471a2b944e9c35c2a6378714c0f885ef115ab4f91a38777f2b.mjs";
export const craftingRuntimes: Readonly<Record<string, HistoricalCraftingRuntime>> = { "crafting-graph-1": runtime0, "crafting-graph-2": runtime1, "crafting-graph-3": runtime2, "crafting-graph-4": runtime3, "crafting-graph-5": runtime4, };
export const craftingRuntimeHashes: Readonly<Record<string, string>> = { "crafting-graph-1": "296f9f16b2e0d52352368ef18c220fc5926eb89ec0f360aef0456c191efbd8b1", "crafting-graph-2": "b57317f7f65b2ea389c23aceccb86932e9e7d431793467b11f8b88a145a7e802", "crafting-graph-3": "04c86b667516300ef56642d9e6c220a76e4c9be0a5c363e4b93fc263c26c7d1f", "crafting-graph-4": "e7614802f36cc80d556ce55837ca5844e92674f3c76f659dcc10d0ccd0b984c2", "crafting-graph-5": "cbcbe51dc69b80471a2b944e9c35c2a6378714c0f885ef115ab4f91a38777f2b", };
